#!/bin/bash

source ./paths.sh
source ./str_manipulator.sh

function generate_view()
{
    upper_case_feature_name=$(get_upper_case_feature_name $1)
        
    echo "import 'package:flutter/material.dart';
import '../controllers/implementations/${1}_controller_impl.dart';

class ${upper_case_feature_name}View extends View {
  static get routeName => '/${upper_case_feature_name}'
  final ${upper_case_feature_name}ControllerImpl controllerImpl;

  @override
  _${upper_case_feature_name}ViewState generateState() => _${upper_case_feature_name}ViewState(controllerImpl);
}

class _${upper_case_feature_name}ViewState extends ViewState<${upper_case_feature_name}View, ${upper_case_feature_name}ControllerImpl> {

  _${upper_case_feature_name}ViewState(${upper_case_feature_name}ControllerImpl controllerImpl) : super(controllerImpl);

  @override
  void initState() {
  super.initState();
  }

  @override
  Widget buildPage() {
    return Scaffold(
      resizeToAvoidBottomPadding: false,
      key: globalKey,
      body: Center(child:Text('Generated by flugen.'))
    )
  }
}

    ">"${VIEWS_DIR}/${1}_view.dart"
}